(() => {
let products=JSON.parse(JSON.stringify(window.SBMG_PRODUCTS||[])),settings=JSON.parse(JSON.stringify(window.SBMG_SETTINGS||{}));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.panel').forEach(p=>p.classList.toggle('active',p.id===b.dataset.tab))});
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
function field(label,key,value,type='text',cls=''){return `<div class="field ${cls}"><label>${label}</label>${type==='textarea'?`<textarea data-key="${key}">${esc(value)}</textarea>`:`<input type="${type}" data-key="${key}" value="${esc(value)}">`}</div>`}
function renderProducts(){const el=$('#productEditor');el.innerHTML=products.map((p,i)=>{const imgs=Array.isArray(p.images)?[...p.images]:[p.image||''];while(imgs.length<3)imgs.push('');return `<article class="editor-card"><div class="editor-top"><h3>${esc(p.name||'New Product')}</h3><button class="btn danger delete">Delete</button></div><div class="form-grid">${field('Product Name','name',p.name,'text','wide')}${field('Category','category',p.category)}${field('Collection','collection',p.collection)}${field('Age','age',p.age)}${field('Sizes','sizes',p.sizes)}${field('Fabric','fabric',p.fabric)}${field('GSM','gsm',p.gsm)}${field('Badge','badge',p.badge)}${field('Photo 1 Path','image0',imgs[0])}${field('Photo 2 Path','image1',imgs[1])}${field('Photo 3 Path','image2',imgs[2])}${field('Short Description','description',p.description,'textarea','full')}${field('Full Product Details','details',p.details,'textarea','full')}</div></article>`}).join('');
el.querySelectorAll('.editor-card').forEach((card,i)=>{card.querySelectorAll('[data-key]').forEach(inp=>inp.oninput=()=>{const k=inp.dataset.key;if(k.startsWith('image')){const n=Number(k.replace('image',''));if(!Array.isArray(products[i].images))products[i].images=[];products[i].images[n]=inp.value}else products[i][k]=inp.value});card.querySelector('.delete').onclick=()=>{products.splice(i,1);renderProducts()}})}
function renderSettings(){const keys=[['Brand Name','brand'],['WhatsApp Number (country code, no +)','whatsapp'],['Phone Display','phoneDisplay'],['Email','email'],['Address','address'],['Default WhatsApp Message','whatsappMessage']];$('#settingsEditor').innerHTML=keys.map(([l,k])=>field(l,k,settings[k],k==='whatsappMessage'?'textarea':'text',k==='whatsappMessage'?'full':'')).join('');$('#settingsEditor').querySelectorAll('[data-key]').forEach(inp=>inp.oninput=()=>settings[inp.dataset.key]=inp.value)}
function download(name,content){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/javascript'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('#addProduct').onclick=()=>{products.push({id:'product-'+Date.now(),name:'New Product',category:'Boys',collection:'Summer',age:'3–7 Years',sizes:'3, 4, 5, 6, 7',fabric:'Single Jersey',gsm:'190 GSM',badge:'New',images:['images/products/photo-1.jpg','images/products/photo-2.jpg','images/products/photo-3.jpg'],description:'',details:''});renderProducts()};
$('#exportProducts').onclick=()=>{products.forEach(p=>{p.images=(p.images||[]).filter(Boolean).slice(0,3);delete p.image});download('products.js','window.SBMG_PRODUCTS = '+JSON.stringify(products,null,2)+';\n')};
$('#exportSettings').onclick=()=>download('settings.js','window.SBMG_SETTINGS = '+JSON.stringify(settings,null,2)+';\n');
renderProducts();renderSettings();
})();