const KEY='sbmg_catalogues_draft_v1';let data=JSON.parse(localStorage.getItem(KEY)||'null')||(window.SBMG_CATALOGUES||[]).map(x=>({...x}));const list=document.getElementById('list'),modal=document.getElementById('modal'),form=document.getElementById('form');
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function render(){list.innerHTML=data.map((c,i)=>`<div class="item"><div><h3>${esc(c.title)}</h3><div class="meta">${esc(c.season)} ${esc(c.year)} • ${esc(c.pdf)}</div></div><div class="actions"><button onclick="editItem(${i})">Edit</button><button class="delete" onclick="deleteItem(${i})">Delete</button></div></div>`).join('')||'<p>No catalogue added.</p>'}
function openForm(i=''){form.reset();document.getElementById('editIndex').value=i;if(i!==''){const c=data[i];['title','season','year','description','pdf','cover','badge'].forEach(k=>document.getElementById(k).value=c[k]||'');document.getElementById('formTitle').textContent='Edit Catalogue'}else document.getElementById('formTitle').textContent='Add Catalogue';modal.classList.add('open')}
window.editItem=i=>openForm(i);window.deleteItem=i=>{if(confirm('Delete this catalogue?')){data.splice(i,1);save()}};
document.getElementById('addBtn').onclick=()=>openForm();document.getElementById('closeBtn').onclick=()=>modal.classList.remove('open');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
form.onsubmit=e=>{e.preventDefault();const obj={id:document.getElementById('title').value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),title:document.getElementById('title').value.trim(),season:document.getElementById('season').value.trim(),year:document.getElementById('year').value.trim(),description:document.getElementById('description').value.trim(),pdf:document.getElementById('pdf').value.trim(),cover:document.getElementById('cover').value.trim(),badge:document.getElementById('badge').value.trim()};const i=document.getElementById('editIndex').value;if(i==='')data.push(obj);else data[Number(i)]=obj;save();modal.classList.remove('open')};
document.getElementById('exportBtn').onclick=()=>{const content='window.SBMG_CATALOGUES = '+JSON.stringify(data,null,2)+';\n';const blob=new Blob([content],{type:'application/javascript'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='catalogues.js';a.click();URL.revokeObjectURL(a.href)};
document.getElementById('resetBtn').onclick=()=>{if(confirm('Remove browser changes and reload original catalogues.js?')){localStorage.removeItem(KEY);location.reload()}};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab+'Panel').classList.add('active')});render();
