const WHATSAPP='919842886717';
const waText=encodeURIComponent('Hello SBMG Textiles, I would like to know more about your wholesale kidswear collections.');
document.querySelectorAll('.whatsapp-link').forEach(a=>{a.href=`https://wa.me/${WHATSAPP}?text=${waText}`;a.target='_blank';a.rel='noopener'});
document.getElementById('year').textContent=new Date().getFullYear();
const menu=document.querySelector('.menu-btn'),nav=document.querySelector('.nav');menu?.addEventListener('click',()=>nav.classList.toggle('open'));nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const products=window.SBMG_PRODUCTS||window.products||[];const grid=document.getElementById('productGrid');const filters=document.getElementById('filters');
function label(v){return typeof v==='object'?(v.en||Object.values(v)[0]):v}
function productSVG(color='#2b8ca3'){return `<svg viewBox="0 0 320 320" aria-hidden="true"><path d="M90 55l70-35 70 35 58 55-45 48-27-27v155q-56 26-112 0V131l-27 27-45-48z" fill="${color}"/><path d="M132 47q28 28 56 0" fill="none" stroke="rgba(255,255,255,.55)" stroke-width="16" stroke-linecap="round"/><path d="M118 165h84" stroke="white" stroke-opacity=".8" stroke-width="13" stroke-linecap="round"/></svg>`}
function renderProducts(filter='All'){if(!grid)return;const list=filter==='All'?products:products.filter(p=>label(p.category)===filter||p.type===filter);grid.innerHTML=list.map(p=>{const image=p.image&&p.image.trim()?`<img src="${p.image}" alt="${label(p.name)}" onerror="this.outerHTML='${productSVG(p.palette?.[0]||'#2b8ca3').replaceAll("'","&apos;")}'">`:productSVG(p.palette?.[0]||'#2b8ca3');return `<article class="product-card reveal visible"><div class="product-visual" style="background:${p.palette?.[1]||'#eef4f2'}"><span class="badge">${p.badge||'Wholesale'}</span>${image}</div><div class="product-body"><h3>${label(p.name)}</h3><div class="product-sub">${label(p.category)||p.type||'Kidswear'}</div><div class="product-detail">Sizes: ${Array.isArray(p.sizes)?p.sizes.join(', '):(p.sizes||'Ask us')} • ${p.fabric||'Knitted fabric'}${p.gsm?' • '+p.gsm+' GSM':''}</div><a class="product-link whatsapp-link" target="_blank" href="https://wa.me/${WHATSAPP}?text=${encodeURIComponent('Hello SBMG Textiles, I am interested in '+label(p.name)+'. Please share wholesale details.')}">Enquire about this style →</a></div></article>`}).join('')||'<p>No products found.</p>'}
if(filters){const cats=['All',...new Set(products.map(p=>label(p.category)||p.type).filter(Boolean))];filters.innerHTML=cats.map((c,i)=>`<button class="filter-btn ${i===0?'active':''}">${c}</button>`).join('');filters.addEventListener('click',e=>{if(!e.target.matches('button'))return;filters.querySelectorAll('button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');renderProducts(e.target.textContent)})}renderProducts();
const catGrid=document.getElementById('catalogueGrid');const catalogues=window.SBMG_CATALOGUES||[];if(catGrid){catGrid.innerHTML=catalogues.map(c=>`<article class="catalogue-card reveal"><div class="catalogue-cover">${c.cover?`<img src="${c.cover}" alt="${c.title}">`:''}<span class="catalogue-badge">${c.badge||'Catalogue'}</span><small>${c.season||'COLLECTION'} • ${c.year||''}</small><h3>${c.title}</h3></div><div class="catalogue-body"><p>${c.description||''}</p><div class="catalogue-actions"><a href="${c.pdf}" target="_blank">View PDF</a><a href="${c.pdf}" download>Download</a></div></div></article>`).join('')||'<p>No catalogues added yet.</p>'}
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
